// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: proto/scorer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MLScorer_Score_FullMethodName = "/scorer.MLScorer/Score"
)

// MLScorerClient is the client API for MLScorer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MLScorerClient interface {
	Score(ctx context.Context, in *FeatureVector, opts ...grpc.CallOption) (*ScoreResponse, error)
}

type mLScorerClient struct {
	cc grpc.ClientConnInterface
}

func NewMLScorerClient(cc grpc.ClientConnInterface) MLScorerClient {
	return &mLScorerClient{cc}
}

func (c *mLScorerClient) Score(ctx context.Context, in *FeatureVector, opts ...grpc.CallOption) (*ScoreResponse, error) {
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, MLScorer_Score_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLScorerServer is the server API for MLScorer service.
// All implementations must embed UnimplementedMLScorerServer
// for forward compatibility
type MLScorerServer interface {
	Score(context.Context, *FeatureVector) (*ScoreResponse, error)
	mustEmbedUnimplementedMLScorerServer()
}

// UnimplementedMLScorerServer must be embedded to have forward compatible implementations.
type UnimplementedMLScorerServer struct {
}

func (UnimplementedMLScorerServer) Score(context.Context, *FeatureVector) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Score not implemented")
}
func (UnimplementedMLScorerServer) mustEmbedUnimplementedMLScorerServer() {}

// UnsafeMLScorerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLScorerServer will
// result in compilation errors.
type UnsafeMLScorerServer interface {
	mustEmbedUnimplementedMLScorerServer()
}

func RegisterMLScorerServer(s grpc.ServiceRegistrar, srv MLScorerServer) {
	s.RegisterService(&MLScorer_ServiceDesc, srv)
}

func _MLScorer_Score_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeatureVector)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLScorerServer).Score(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLScorer_Score_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLScorerServer).Score(ctx, req.(*FeatureVector))
	}
	return interceptor(ctx, in, info, handler)
}

// MLScorer_ServiceDesc is the grpc.ServiceDesc for MLScorer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLScorer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scorer.MLScorer",
	HandlerType: (*MLScorerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Score",
			Handler:    _MLScorer_Score_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/scorer.proto",
}
